# Generated by Django 5.2.6 on 2025-10-01 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default', max_length=100)),
                ('primary_color', models.CharField(default='#667eea', max_length=7)),
                ('primary_dark', models.CharField(default='#764ba2', max_length=7)),
                ('secondary_color', models.CharField(default='#48bb78', max_length=7)),
                ('border_radius', models.CharField(choices=[('sharp', 'Bordes Rectos'), ('normal', 'Bordes Normales'), ('rounded', 'Bordes Redondeados')], default='normal', max_length=20)),
                ('shadow_intensity', models.CharField(choices=[('light', 'Suaves'), ('medium', 'Normales'), ('strong', 'Fuertes')], default='medium', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_active', '-updated_at'],
            },
        ),
    ]
