# Generated by Django 5.2.6 on 2025-11-09 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitetheme',
            name='error_bg',
            field=models.CharField(default='#fed7d7', max_length=7),
        ),
        migrations.AddField(
            model_name='sitetheme',
            name='error_color',
            field=models.CharField(default='#e53e3e', max_length=7),
        ),
        migrations.AddField(
            model_name='sitetheme',
            name='error_dark',
            field=models.CharField(default='#c53030', max_length=7),
        ),
        migrations.AddField(
            model_name='sitetheme',
            name='info_bg',
            field=models.CharField(default='#bee3f8', max_length=7),
        ),
        migrations.AddField(
            model_name='sitetheme',
            name='info_color',
            field=models.CharField(default='#3182ce', max_length=7),
        ),
        migrations.AddField(
            model_name='sitetheme',
            name='info_dark',
            field=models.CharField(default='#2b6cb0', max_length=7),
        ),
        migrations.AddField(
            model_name='sitetheme',
            name='primary_light',
            field=models.CharField(default='#a8b9ff', max_length=7),
        ),
        migrations.AddField(
            model_name='sitetheme',
            name='secondary_dark',
            field=models.CharField(default='#38a169', max_length=7),
        ),
        migrations.AddField(
            model_name='sitetheme',
            name='secondary_light',
            field=models.CharField(default='#9ae6b4', max_length=7),
        ),
        migrations.AddField(
            model_name='sitetheme',
            name='success_bg',
            field=models.CharField(default='#c6f6d5', max_length=7),
        ),
        migrations.AddField(
            model_name='sitetheme',
            name='success_color',
            field=models.CharField(default='#48bb78', max_length=7),
        ),
        migrations.AddField(
            model_name='sitetheme',
            name='success_dark',
            field=models.CharField(default='#2f855a', max_length=7),
        ),
        migrations.AddField(
            model_name='sitetheme',
            name='warning_bg',
            field=models.CharField(default='#ffd89a', max_length=7),
        ),
        migrations.AddField(
            model_name='sitetheme',
            name='warning_color',
            field=models.CharField(default='#ed8936', max_length=7),
        ),
        migrations.AddField(
            model_name='sitetheme',
            name='warning_dark',
            field=models.CharField(default='#c05621', max_length=7),
        ),
    ]
