# Generated by Django 5.2.6 on 2025-09-20 07:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0010_alter_pedido_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallepedido',
            name='producto',
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='nombre_producto',
            field=models.CharField(default='Producto sin nombre', max_length=255),
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='producto_id',
            field=models.UUIDField(default=uuid.uuid4, help_text='UUID del producto en Cassandra'),
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
