# Generated by Django 5.2.6 on 2025-10-01 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtributoSubcategoria',
            fields=[
            ],
            options={
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='AtributoCategoria',
        ),
    ]
