# Generated by Django 5.2.6 on 2025-10-01 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='estado_cuenta_usuario',
            field=models.CharField(default='activo', max_length=20),
        ),
    ]
